<a href="https://colab.research.google.com/github/Marwaway/My-AI-Journey-/blob/main/MRI%20normalizion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
# example of broadcasting
# mimics how data is normalized on medical AI

# MRI scan data (3 patients, 4 biomarkers)
A = np.array([[56, 0, 4, 68],
              [1, 10, 52, 8],
              [1, 33, 99, 0.9]])
print("Original MRI scan intensities:\n", A)


calc = A.sum(axis=0)
print("\nColumn sums (total biomarkers):\n", calc)


# Calculate percentages
# we reshape to avoid rank 1 array they are missed up
percentages = 100 * A / A.sum(axis=0).reshape(1, 4)
print("\nNormalized percentages:\n", percentages)


# Show results
print("Normalized MRI Data:\n", percentages)

# Download the file on phone
from google.colab import files
np.savetxt("mri_results.txt", percentages, fmt="%.2f")
files.download("mri_results.txt")

Original MRI scan intensities:
 [[56.   0.   4.  68. ]
 [ 1.  10.  52.   8. ]
 [ 1.  33.  99.   0.9]]

Column sums (total biomarkers):
 [ 58.   43.  155.   76.9]

Normalized percentages:
 [[96.55172414  0.          2.58064516 88.42652796]
 [ 1.72413793 23.25581395 33.5483871  10.40312094]
 [ 1.72413793 76.74418605 63.87096774  1.17035111]]
Normalized MRI Data:
 [[96.55172414  0.          2.58064516 88.42652796]
 [ 1.72413793 23.25581395 33.5483871  10.40312094]
 [ 1.72413793 76.74418605 63.87096774  1.17035111]]


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>