<a href="https://colab.research.google.com/github/Marwaway/My-AI-Journey-/blob/main/MRI%20preprocessing%2C%20multiple%20intensity%20normalization%20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
import numpy as np
import time

# Simulate 100 MRI scans (256x256) with random intensities (0-5000)
mriscans = np.random.randint(0, 5000, size=(100, 256, 256))
print ("MRI scans intensities : \n", mriscans)

# Vectorized normalization per scan
normalizedmri = (mriscans - mriscans.min(axis=(1,2), keepdims=True)) / (mriscans.max(axis=(1,2), keepdims=True) - mriscans.min(axis=(1,2), keepdims=True))
print(" MRI normalize intensities : \n", normalizedmri)
#- What it does: Finds the minimum pixel value*for each scan- axis=(1,2) : Compute min across height (axis 1) AND width (axis 2)- keepdims=True: Preserves dimensions as `(100, 1, 1)` instead of `(100,)`

# Check min/max of the normalized data (should be ~0 and ~1)
print("Global min:", normalizedmri.min())  # Expected: ~0.0
print("Global max:", normalizedmri.max())  # Expected: ~1.0

# Check min/max for a single scan (e.g., scan 0)
print("Scan min:", normalizedmri[0].min())  # Should be 0.0
print("Scan max:", normalizedmri[0].max())  # Should be 1.0
print("Confirms that the normalized MRI array retains the original shape :\n ", normalizedmri.shape)

MRI scans intensities : 
 [[[4348 1453 3346 ...  526 3881 2427]
  [2282 3985 1679 ... 2181 2022 2567]
  [3749 2844 1186 ... 1103 2315 2249]
  ...
  [4936 2556 4131 ... 2167 2214  902]
  [2397  824 3589 ... 3682 1583 3398]
  [3944 2492 1240 ... 2489 1109 1402]]

 [[ 993 1664 3568 ... 2057 3667 3083]
  [ 735 2086 2605 ... 1175 3743 2396]
  [ 184 4526  166 ... 2709  750 3156]
  ...
  [ 968 2253 2792 ...  703 1583 2972]
  [1490 2238 2962 ... 2295 3694 3514]
  [3554 1515  946 ...  949 1987 2559]]

 [[1150  324 4145 ... 4074  569 2495]
  [1576 4358 1971 ...  122 1421 3673]
  [4833 4579 2548 ... 4946  260 1912]
  ...
  [2205 1443 1835 ... 3795 2696 4303]
  [4542 2713 2881 ... 3320 2656 2643]
  [ 581 2487 2699 ...  206 1626 2000]]

 ...

 [[1121  577  200 ... 1810 4454 1280]
  [ 758 4937 1462 ... 1940 4622 4361]
  [2706 4317  339 ... 3496   60  703]
  ...
  [ 990 1242 2529 ... 1867 3243 1525]
  [3942 2114 1577 ...  805 1331  972]
  [1448 2105 2890 ...   49 3735 3616]]

 [[3622 1247 3282 ... 39